USE [WSS_Content]
GO

/****** Object:  Table [dbo].[TSK_DURATION_PLAN_LOG]    Script Date: 06.02.2025 15:59:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TSK_DURATION_PLAN_LOG](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[TASK_ID] [uniqueidentifier] NOT NULL,
	[DURATION] [decimal](10, 4) NOT NULL,
	[DATE] [datetime] NULL,
 CONSTRAINT [TSK_DURATION_PLAN_LOG_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = ON, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

