USE [WSS_Content]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




CREATE PROCEDURE [dbo].[TSK_AddUserPositionHistory]
AS

BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	DECLARE @CURRENT_DATE AS DATE
	SET @CURRENT_DATE = CURRENT_TIMESTAMP

	DELETE FROM TSK_USER_POSITION_HISTORY WHERE [DATE] = @CURRENT_DATE

	INSERT INTO TSK_USER_POSITION_HISTORY ([USER_ID] ,[USER_ORG_ID] ,[POSITION_ID], [PARENT_ORG_ID], [DESIGN_CENTER_ID] ,[DATE] ,[CREATE_TIME])
	SELECT  [QRY_USER_ID_POSITION_ID].[UserId], [QRY_USER_ID_POSITION_ID].[OrgId], [QRY_USER_ID_POSITION_ID].[PositionId], 
	[QRY_USER_ID_POSITION_ID].[ParentOrgId],[QRY_USER_ID_POSITION_ID].[DesignCenterId],
	@CURRENT_DATE, CURRENT_TIMESTAMP  FROM 
	[QRY_USER_ID_POSITION_ID] where [QRY_USER_ID_POSITION_ID].[UserId] is not null and [QRY_USER_ID_POSITION_ID].[PositionId] is not null and [QRY_USER_ID_POSITION_ID].[OrgId] is not null

END





GO

