USE [WSS_Content]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TSK_PROJECT_LIST_STATUS_HISTORY](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[PROJECT_ID] [int] NOT NULL,
	[PROJECT_UNIQUE_ID] [uniqueidentifier] NOT NULL,
	[STATUS_ID] [int] NOT NULL,
	[DATE] [date] NOT NULL,
	[CREATE_TIME] [datetime] NOT NULL,
 CONSTRAINT [TSK_PROJECT_STATUS_HISTORY_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = ON, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

