USE [WSS_Content]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[REP_AddUserSalaryHistory]
AS

BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	DECLARE @CURRENT_DATE AS DATE
	SET @CURRENT_DATE = CURRENT_TIMESTAMP

	DELETE FROM [USER_SALARY_HISTORY] WHERE [DATE] = @CURRENT_DATE

	INSERT INTO [USER_SALARY_HISTORY] ([PERSON_ID], [LOGIN_ID], [ORG_ID], [PERSON_NUM], [SALARY], [DATE], [CREATE_TIME])
	SELECT  [QRY_USER_SALARY].[PersonId], [QRY_USER_SALARY].[LoginId], [QRY_USER_SALARY].[OrgId],
	[QRY_USER_SALARY].[PersonNum], [QRY_USER_SALARY].[Salary],
	@CURRENT_DATE, CURRENT_TIMESTAMP  FROM 
	[QRY_USER_SALARY] where [QRY_USER_SALARY].[PersonId] is not null and [QRY_USER_SALARY].[OrgId] is not null

END

GO